# Directories arguments
data_root: "/media/DATA/HEVI_dataset/fol_data"
ego_data_root: "/media/DATA/HEVI_dataset/ego_motion"
checkpoint_dir: "checkpoints/fol_ego_checkpoints"

best_ego_pred_model: "checkpoints/ego_pred_checkpoints/epoch_080_loss_0.001.pt"
test_dataset: "taiwan_sa" #"A3D" #"taiwan_sa"
test_root: #"../data/taiwan_sa/testing" #"/media/DATA/A3D" #"/media/DATA/VAD_datasets/taiwan_sa/testing" AnAnAccident_Detection_Dataset
label_file: '../data/A3D/A3D_labels.pkl'

# dataset arguments
seed_max: 5
segment_len: 16

# training parameters
nb_fol_epoch: 100
nb_ego_pred_epoch: 200
lr: 0.0001

lambda_fol: 1
lambda_ego: 1
device: 'cuda'

# fol model parameters
pred_timesteps: 15
input_embed_size: 512
flow_enc_size: 512
box_enc_size: 512
with_ego: True

enc_hidden_size: 512 # no use
enc_concat_type: "average"
predictor_input_size: 512
dec_hidden_size: 512
pred_dim: 4


# ego_pred model parameters
ego_embed_size: 128
ego_enc_size: 128
ego_dec_size: 128
ego_pred_input_size: 128
ego_dim: 3

# dataloader parameters
batch_size: 32
shuffle: True
num_workers: 0

# image parameters
H: 720
W: 1280
channels: 3

flow_roi_size: [5,5,2]

# Anomaly detection parameters
max_age: 10
